### ISSUE TITLE
Calendar not showing if bad event exists (doesn’t tell which one)

### ISSUE THREAD

**Issue by surak** [aceisace/Raspberry-Pi-Setup#1]
Hi, I have the calendar showing a blank, like this: 
![7CBEE995-F722-4745-A490-E3ED22DDF66D](https://user-images.githubusercontent.com/878399/75425642-67f4d180-5943-11ea-8214-956627b33a39.jpeg)

Turn out that, it I stop the supervisor and run it manually, I can see why:

![B9FC4AE9-091F-43BC-9D68-754B73344E96](https://user-images.githubusercontent.com/878399/75425765-9ffc1480-5943-11ea-92be-91ff47a3951e.jpeg)

Perhaps a notification on the lower (event) area instead of showing nothing would have been more descriptive? I don’t even know which event is wrong so I could delete it.

**Comment by aceisace** [comment]
Oh, haven't checked this repo for a long time now, apologies for the late reply. I think you missed the right repo 😅.

Closing this issue

**Comment by surak** [comment]
Wow, bug #1! This project has gone a long way!
